run_name: null
data_path: ${hydra:runtime.cwd}/naip_data/augmented

trainer:
  resume_from_checkpoint: null
  precision: bf16-mixed

model:
  model_name: Basic
  encoder_name: resnet18
  embedding_size: 128
  distance_name: EuclideanDistance
  miner_name: BatchHardMiner
  loss_function_name: TripletMarginLoss
  lr: 3e-4
  lr_patience: 10

datamodule:
  augment: True
  data_path: ${data_path}
  num_of_workers: 24
  num_of_places_per_batch: 15
  num_of_images_per_place: 5
  num_of_batches_per_epoch: 2000
  validation_batch_size: 128

logger:
  api_key: ${oc.env:NEPTUNE_API_TOKEN}
  project: Vision/PlaceRecognition
  log_model_checkpoints: false
  name: ${run_name}